default:  fxctmp9_tmp\parallaxtest_ps30.inc fxctmp9_tmp\parallaxtest_vs30.inc

fxctmp9_tmp\parallaxtest_ps30.inc :  parallaxtest_ps30.fxc 
	perl ..\..\devtools\bin\fxc_prep.pl -novcs   -source "..\.." parallaxtest_ps30.fxc-----parallaxtest_ps30

fxctmp9_tmp\parallaxtest_vs30.inc :  parallaxtest_vs30.fxc common_fxc.h common_vs_fxc.h common_hlsl_cpp_consts.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl -novcs   -source "..\.." parallaxtest_vs30.fxc-----parallaxtest_vs30

